# You should change this to match your app name in .platform.app.yaml
name: my-backdrop-app
recipe: backdrop
config:
  webroot: web
  php: '7.0'

services:
  #appserver:
  #  build:
  #    - "curl -sS https://platform.sh/cli/installer | php"
  node-cli:
    type: node:6.10
    build:
      - cd $LANDO_MOUNT && npm install
    globals:
      gulp-cli: "latest"

# See: https://docs.lndo.io/config/tooling.html
tooling:
  npm:
    service: node-cli
  node:
    service: node-cli
  gulp:
    service: node-cli
    #platform:
    #plservice: appserver
    #plcmd: /var/www/.platformsh/bin/platform
